name: ci

on:
  push:
    branches:
      - main
    tags:        
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      # Run audit tools.
      - run: |
          cargo install --locked cargo-deny
          cargo deny check
      # Run linters.
      - run: |
          cargo fmt -- --check
          cargo clippy --tests -- --no-deps -D warnings
      # Run all tests.
      - run: cargo test --no-fail-fast --all-features
