name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUST_VERSION: 1.61

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      # Install cargo plugins.
      - run: |
          rustup component add rustfmt clippy
          cargo install --locked cargo-deny
      # Run audit tools.
      - run: cargo deny check
      # Run linters.
      - run: |
          cargo fmt -- --check
          cargo clippy --tests -- --no-deps -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - run: cargo test --no-fail-fast
